### ISSUE TITLE
Add support for Govee Lyra RGBICWW Corner Floor Lamp (H6072)

### ISSUE THREAD

**Issue by nfourtythree** [constructorfleet/homebridge-ultimate-govee#133]
It would be great if support for the H6072 lamp could be added to the plugin.

**Comment by Teagan42** [comment]
Sure. Does this light support segments? (If you go to the Govee App, go to your light there is a diagram of your light with some options along the light) If it does - how many segments does it have? Adding the light is pretty simple, however it may not be perfect. I spent a lot of time reverse engineering the communication protocols with every device I could get my hands on and most follow the same pattern - but some do not.

![image](https://user-images.githubusercontent.com/2989925/225479087-cf6c3981-8ad0-4213-b49e-dd413f117cbb.png)

**Comment by Teagan42** [comment]
Technically this is an RGBICWW - which I haven't had a chance to determine the commandset. I made an assumption that it follows the RGBIC commands. Try the latest release 2.88.0 - if it doesn't behave acceptably I will have to pull it out of the code
