### ISSUE TITLE
Humidity reporting always 0%

### ISSUE THREAD

**Issue by ignacio82** [constructorfleet/homebridge-ultimate-govee#265]
This is the one you just added to the integration:

![image](https://github.com/constructorfleet/homebridge-ultimate-govee/assets/1833309/69f63363-9cca-45cf-9fd2-6bde14c6adb7)

![image](https://github.com/constructorfleet/homebridge-ultimate-govee/assets/1833309/25743086-6121-487f-932e-a1fbf5de098d)

with the official app:

![image](https://github.com/constructorfleet/homebridge-ultimate-govee/assets/1833309/5aea618c-9e56-4c93-b73e-b93dbe4a68ac)

And this is the big one

![image](https://github.com/constructorfleet/homebridge-ultimate-govee/assets/1833309/84a9f27d-803c-4b50-8363-da035a2c3643)

![image](https://github.com/constructorfleet/homebridge-ultimate-govee/assets/1833309/96634e13-adfe-4fcb-aaa9-50a5075817eb)

with the other homebridge pluging 

![image](https://github.com/constructorfleet/homebridge-ultimate-govee/assets/1833309/bab15217-13fd-46c5-992c-412cd9916cf3)

with the official app

![image](https://github.com/constructorfleet/homebridge-ultimate-govee/assets/1833309/60e3faa8-ad93-417a-8d15-e28e96b933b5)

I also noticed that both humidifiers say the target is normal when is actually set to auto in the app.

**Comment by Teagan42** [comment]
I will add it to my todo list. All of these values and commands have to be reverse engineered from HEX codes - Govee's developer API/SDK exposes very little about the devices: on, off, color, brightness, color temperature. (https://govee-public.s3.amazonaws.com/developer-docs/GoveeDeveloperAPIReference.pdf - you will see, the control and data they provide open source developers is majorly lacking)

I spent over 2 months borrowing friends' govee devices and decoding the commands and responses - e.g. is schedule active, how long was the schedule and how much time remains, humidifer custom mode (each of the mist levels, durations,  which one is active and for how long) or locking the controls or turning on/off the control panel lights on purifiers. But when it comes to devices I don't have or devices with new features, it becomes tricky. https://blog.teagantotally.rocks/2022/02/12/the-ultimate-govee-homebridge-plugin/

I'm pretty sure somewhere in my decoding notes I have the target humidity and value for the auto mode, so bare with me I'll get to it. But as more people are asking for devices, I think it's time to provide the users with the logs and instructions to allow me to decode the commands/state/responses for their devices. I have many projects going, not too many picked up traction except this one.
